#!/usr/bin/env bash

# /opt/lxd-executor/base.sh

CONTAINER_IMAGE=${CUSTOM_ENV_LXC_IMAGE:-"images:centos/7"}
CONTAINER_DISTRO=${CONTAINER_IMAGE#*:}
CONTAINER_DISTRO=${CONTAINER_DISTRO%/*}
CONTAINER_DISTRO_VERSION=${CONTAINER_IMAGE#*/}
CONTAINER_ID="runner-$CUSTOM_ENV_CI_RUNNER_ID-project-$CUSTOM_ENV_CI_PROJECT_ID-concurrent-$CUSTOM_ENV_CI_CONCURRENT_PROJECT_ID-$CONTAINER_DISTRO-$CONTAINER_DISTRO_VERSION"
