---
prometheus_version: 2.12.0

prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/local/prometheus

prometheus_web_listen_address:
prometheus_web_listen_port: 9090
prometheus_web_external_url:
