---
- name: synchronize dockerhost
  copy:
    src: mattermost-docker/
    dest: "{{ mattermost_docker_path }}"
    force: false

- name: docker image app
  docker_image:
    name: mattermost_ap
    build:

- name: build db container
  docker_image:
    name: mattermost_db
