---

- hosts: k8s
  user: root
#  roles:
#  - common
  tasks:
  - name: install epel-release
    yum:
      name:
      - epel-release
  - name: install openldap
    yum:
      name:
      - openldap
      - openldap-clients
      - openldap-servers
      - gcc
      - python2-devel
      - openldap-devel
      - python2-pip
  - name: install python-pip
    pip:
      name: python-ldap


