---
- name: gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_architecture | lower }}/{{ ansible_os_family | lower }}.yml"
  - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_os_family | lower }}.yml"
  tags: always

- name: loop
  when: selfsigned_cert_fqdn | type_debug == 'dict'
  include: item.yml
  with_dict:
  - "{{ selfsigned_cert_fqdn }}"
  tags: reconfigure

- name: put gossfile
  when: goss_dir is defined
  template:
    src: goss.yml.j2
    dest: "{{ goss_dir }}/selfsigned-cert.yml"
    owner: root
    group: root
    mode: '0600'
  tags: reconfigure
