---

- include: "install_{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"

- name: start iptables
  service:
    name: iptables
    state: started
    enabled: yes

- name: start ip6tables
  service:
    name: ip6tables
    state: started
    enabled: yes

- name: put goss
  copy:
    dest: /usr/local/share/goss/iptables.yml
    content: |
      service:
        iptables:
          enabled: true
        ip6tables:
          enabled: true
