---
- name: elasticsearch reload
  become: true
  service:
    name: elasticsearch
    state: reloaded

- name: elasticsearch restart
  become: true
  service:
    name: elasticsearch
    state: restarted
