---
- name: dockerパッケージを配置
  copy:
    src: redmine-docker/
    dest: "{{ redmine_docker_path }}"
  tags: redmine

- name: githubからredmineリポジトリをpull
  git:
    repo: https://github.com/redmine/redmine.git
    dest: "{{ redmine_docker_path }}/app/redmine"
    version: "{{ redmine_docker_branch }}"
  tags: redmine

- name: データベース設定ファイルを配置
  copy:
    dest: "{{ redmine_docker_path }}/app/redmine/config/database.yml"
    content: |
      production:
        adapter: postgresql
        database: redmine_production
        host: db
        username: {{ redmine_docker_db_username }}
        password: "{{ redmine_docker_db_password }}"
        encoding: utf8
  tags: redmine

- name: グローバル設定ファイルを配置
  template:
    src: configuration.yml.j2
    dest: "{{ redmine_docker_path }}/app/redmine/config/configuration.yml"
  tags: redmine

- name: 追加環境設定ファイルを配置
  template:
    src: additional_environment.yml
    dest: "{{ redmine_docker_path }}/app/redmine/config/additional_environment.yml"
  tags: redmine

- name: dbコンテナをビルド
  docker_image:
    name: redmine_db
    source: build
    build:
      path: "{{ redmine_docker_path }}/db/"
      pull: no
    force_source: yes
  notify: redmine_docker restart db
  tags: redmine

- name: appコンテナをビルド
  docker_image:
    name: redmine_app
    source: build
    build:
      path: "{{ redmine_docker_path }}/app/"
      pull: no
    force_source: yes
  notify: redmine_docker restart app
  tags: redmine

- name: webコンテナをビルド
  docker_image:
    name: redmine_web
    source: build
    build:
      path: "{{ redmine_docker_path }}/web/"
      pull: no
    force_source: yes
  notify: redmine_docker restart web
  tags: redmine

- name: ホストネットワークを作成
  docker_network:
    name: redmine
  notify:
    - redmine_docker restart db
    - redmine_docker restart app
    - redmine_docker restart web
  tags: redmine

- name: dbコンテナの起動確認
  shell: docker inspect redmine_db | jq -r .[].State.Status
  register: result
  changed_when: result.stdout != "running"
  notify: redmine_docker restart db
  tags: redmine

- name: appコンテナの起動確認
  shell: docker inspect redmine_app | jq -r .[].State.Status
  register: result
  changed_when: result.stdout != "running"
  notify: redmine_docker restart app
  tags: redmine

- name: webコンテナの起動確認
  shell: docker inspect redmine_web | jq -r .[].State.Status
  register: result
  changed_when: result.stdout != "running"
  notify: redmine_docker restart web
  tags: redmine
