---
  
- name: configure iptables
  template:
    src: "{{ iptables.file }}"
    dest: "{{ os_spec.iptables }}"
    mode: 0600
    validate: iptables-restore -t %s
  when:
    - iptables is defined
    - iptables.file is defined
  notify: reload iptables
  tags: iptables

- name: configure ip6tables
  template:
    src: "{{ ip6tables.file }}"
    dest: "{{ os_spec.ip6tables }}"
    mode: 0600
    validate: ip6tables-restore -t %s
  when:
    - ip6tables is defined
    - ip6tables.file is defined
  notify: reload ip6tables
  tags: iptables
