---
prometheus_server_listen_addr: '127.0.0.1'
prometheus_alertmanager_listen_addr: '127.0.0.1'
prometheus_node_exporter_listen_addr: '127.0.0.1'
prometheus_blackbox_exporter_listen_addr: '127.0.0.1'
