---
prometheus_htpasswd: /etc/nginx/.htpasswd

prometheus_server_version: 2.16.0
prometheus_server_listen_addr: '::'

prometheus_alertmanager_version: 0.20.0
prometheus_alertmanager_listen_addr: '::'

prometheus_node_exporter_version: 0.18.1
prometheus_node_exporter_listen_addr: '::'

prometheus_blackbox_exporter_version: 0.16.0
prometheus_blackbox_exporter_listen_addr: '::'

selfsigned_cert_fqdn: "{{ ansible_fqdn }}"
selfsigned_cert_cert_dir: /etc/nginx/
selfsigned_cert_private_dir: /etc/nginx/

nginx_server_http_enable: no
nginx_server_https_enable: yes
nginx_server_location:
  '/':
    proxy_pass: http://127.0.0.1:9090/
    auth_basic: Restricted
    auth_basic_user_file: "{{ prometheus_htpasswd }}"

nginx_server_ssl_certificate: /etc/nginx/www.example.com.crt
nginx_server_ssl_certificate_key: /etc/nginx/www.example.com.key
