---
- name: redmine_docker restart db
  docker_container:
    name: redmine_db
    image: redmine_db
    state: started
    restart: yes
    recreate: yes
    #read_only: yes
    restart_policy: unless-stopped
    networks:
      - name: redmine
    networks_cli_compatible: no
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ redmine_docker_volumes }}/db:/var/lib/postgresql/data:rw"
    env:
      POSTGRES_USER: "{{ redmine_docker_db_username }}"
      POSTGRES_PASSWORD: "{{ redmine_docker_db_password }}"
      POSTGRES_DB: redmine_production

- name: redmine_docker restart app
  docker_container:
    name: redmine_app
    image: redmine_app
    state: started
    restart: yes
    recreate: yes
    #read_only: yes
    restart_policy: unless-stopped
    networks:
      - name: redmine
    networks_cli_compatible: no
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    links:
      - "redmine_db:db"

- name: redmine_docker restart web
  docker_container:
    name: redmine_web
    image: redmine_web
    state: started
    restart: yes
    recreate: yes
    #read_only: yes
    restart_policy: unless-stopped
    networks:
      - name: redmine
    networks_cli_compatible: no
    links:
      - "redmine_app:app"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    published_ports:
      - "{{ redmine_docker_http_port }}:80"
      - "{{ redmine_docker_https_port }}:443"
