---

- include: install-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: enable docker
  service:
    name: docker
    state: started
    enabled: yes
  tags: k8s

- name: enable kubelet
  service:
    name: kubelet
    state: started
    enabled: yes
  tags: k8s
