---
# LISTENアドレスとポート番号を指定する。ポート番号を省略した場合は 22 になる。
sshd_listen:
- v4: 0.0.0.0
- v6: '::'
#- { v4: 127.0.0.1, port: 12345 }

# パスワード認証を許可するか
sshd_allow_password: no    # 許可しない(公開鍵認証のみ)
#sshd_allow_password: yes   # 許可する

# root のSSH接続を許可するか
sshd_permit_root_login: no                      # 許可しない
#sshd_permit_root_login: yes                     # 許可する(非推奨)
#sshd_permit_root_login: prohibit-password       # パスワード認証は不可、公開鍵認証でログインが可能
#sshd_permit_root_login: without-password        # without-password と全く同じ(過去互換のため？)
#sshd_permit_root_login: forced-commands-only    # パスワード認証は不可、公開鍵認証でコマンド実行が可能

# キープアライブ時間を指定する
# 例: 60 interval * 3 count_max = 180 seconds
sshd_keepalive_interval: 0    # (0:無効)
sshd_keepalive_count_max: 3

# ポートフォワーディングを許可するか
sshd_tcp_forwarding: no

# X11フォワーディングするか
sshd_x11_forwarding: no

# internal-sftp を使用するか
sshd_use_internal_sftp: yes
#sshd_user_internal_sftp: no  # レガシーの sftp を使用する

# 接続前に表示させるメッセージを指定する
sshd_banner_file:
#sshd_banner_file: /path/to/banner.txt

# ログレベル
#sshd_log_level: QUIET
#sshd_log_level: FATAL
#sshd_log_level: ERROR
sshd_log_level: INFO
#sshd_log_level: VERBOSE
#sshd_log_level: DEBUG
#sshd_log_level: DEBUG2
#sshd_log_level: DEBUG3
