---
- name: gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_hostname }}.yml"
    - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_architecture | lower }}/{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: [ always ]

# パッケージのインストールする
- name: install
  become: yes
  package:
    name: "{{ chrony_package }}"
  notify: chrony restart

# 設定ファイルをバックアップする
- name: backup the original config file
  become: true
  command: "cp -af {{ chrony_config_file }} {{ chrony_config_file }}.orig"
  args:
    creates: "{{ chrony_config_file }}.orig"

# タイムゾーンを指定する
# timezone module を使用すると相対パスになるので file module を使う
- name: set timezone
  become: yes
  file:
    path: /etc/localtime
    state: link
    src: "/usr/share/zoneinfo/{{ chrony_timezone }}"
    owner: root
    group: root
  notify: chrony restart

# 設定ファイルを作成する
- name: generate chrony.conf
  become: yes
  template:
    src: chrony.conf
    dest: "{{ chrony_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: chrony restart
  tags: [ configure ]

# 自動的に起動する
- name: auto start
  become: yes
  service:
    name: chronyd
    state: started
    enabled: yes

- name: get sha256 in chrony_config_file
  become: yes
  stat:
    path: "{{ chrony_config_file }}"
    checksum_algorithm: sha256
  register: _chrony_config_file_sha256

- name: put gossfile
  become: yes
  template:
    src: goss.yml
    dest: "{{ goss_dir }}/chrony.yml"
    owner: root
    group: root
    mode: 0600
  when: goss_dir is defined
  tags: [ configure ]
