---
- name: タイムゾーンをAsia/Tokyo
  become: yes
  timezone:
    name: Asia/Tokyo
  notify: chrony restart chronyd

- name: インストール
  become: yes
  package:
    name: chrony
  notify: chrony restart chronyd

- name: 設定ファイルをバックアップ
  become: yes
  shell: "cp -af {{ chrony_conf_file }} {{ chrony_conf_file }}.orig"
  args:
    creates: "{{ chrony_conf_file }}.orig"

- name: 初期設定されている接続先NTPサーバを削除
  become: yes
  lineinfile:
    path: "{{ chrony_conf_file }}"
    regexp: '^#?(server\s+.*\.ntp\.org\s+iburst)'
    state: absent
  notify: chrony restart chronyd

- name: 接続先NTPサーバを設定
  become: yes
  blockinfile:
    path: "{{ chrony_conf_file }}"
    insertafter: '^[#!]\s?server\s+'
    block: |
      {% for ip in chrony_ntp_servers %}
      server {{ ip | ipaddr }} iburst
      {% endfor %}
  notify: chrony restart chronyd

- name: 自動起動
  become: yes
  service:
    name: chronyd
    state: started
    enabled: yes
  notify: chrony restart chronyd

- name: テストファイルを配置
  become: yes
  copy:
    owner: root
    mode: '0600'
    content: |
      service:
        chronyd:
          running: true
          enabled: true
      command:
        chronyc activity:
          exit-status: 0
          stdout:
            - " sources online"
            - "!0 sources online"
      file:
        {{ chrony_conf_file }}:
          exists: true
          contains:
      {% for ip in chrony_ntp_servers %}
            - "server {{ ip }} iburst"
      {% endfor %}
        /etc/localtime:
          exists: true
          filetype: symlink
          contains:
            - JST-9
    dest: "{{ goss_dir }}/chrony.yml"
  tags: [ goss ]
