---
- name: タイムゾーンをAsia/Tokyo
  timezone:
    name: Asia/Tokyo
  notify: chrony restart chronyd
  tags: [ chrony ]

- name: インストール
  package:
    name: chrony
  notify: chrony restart chronyd
  tags: [ chrony ]

- name: 設定ファイルをバックアップ
  shell: "cp -af {{ chrony_conf }} {{ chrony_conf}}.org"
  args:
    creates: "{{ chrony_conf }}.org"
  tags: [ chrony ]

- name: 初期設定されている接続先NTPサーバをコメントアウト
  replace:
    dest: "{{ chrony_conf }}"
    regexp: '^(server\s+.*\.ntp\.org\s+iburst)'
    replace: '#\1'
  notify: chrony restart chronyd
  tags: [ chrony ]

- name: 接続先NTPサーバを設定
  blockinfile:
    path: "{{ chrony_conf }}"
    insertafter: '^[#!]\s?server\s+'
    block: |
      {% for ip in chrony_ntp_servers %}
      server {{ ip | ipaddr }} iburst
      {% endfor %}
  notify: chrony restart chronyd
  tags: [ chrony ]

- name: 自動起動
  service:
    name: chronyd
    state: started
    enabled: yes
  notify: chrony restart chronyd
  tags: [ chrony, start ]

- name: テストファイルを配置
  copy:
    content: |
      service:
        chronyd:
          running: true
          enabled: true
      command:
        chronyc activity:
          exit-status: 0
          stdout:
            - " sources online"
            - "!0 sources online"
      file:
        {{ chrony_conf }}:
          exists: true
          contains:
      {% for ip in chrony_ntp_servers %}
            - "server {{ ip }} iburst"
      {% endfor %}
        /etc/localtime:
          exists: true
          filetype: symlink
          contains:
            - JST-9
    dest: "{{ goss_workdir }}/chrony.yml"
  tags: [ chrony, goss ]
