---
- name: Debian固有の変数を取り込む
  include_vars: os_Debian.yml
  when: ansible_os_family == "Debian"

- name: インストール
  package:
    name: sudo

- name: 管理者グループに{{ ansible_ssh_user }}ユーザを追加
  user:
    name: "{{ ansible_ssh_user }}"
    groups:
      - "{{ sudo_wheel }}"
    append: yes

- name: 管理者グループにsudo権限を追加
  lineinfile:
    path: /etc/sudoers
    regexp: "^#?\\s*%{{ sudo_wheel }}\\s+ALL=\\(ALL\\)\\s+ALL"
    line: "%{{ sudo_wheel }} ALL=(ALL) ALL"
    validate: "{{ sudo_executable }} -cf %s"
  when: sudo_ask_pass == True

- name: 管理者グループにsudo権限を追加(パスワード不要)
  lineinfile:
    path: /etc/sudoers
    regexp: "^#?\\s*%{{ sudo_wheel }}\\s+ALL=\\(ALL\\)\\s+ALL"
    line: "%{{ sudo_wheel }} ALL=(ALL) NOPASSWD: ALL"
    validate: "{{ sudo_executable }} -cf %s"
  when: sudo_ask_pass == False

- name: テストファイルを配置
  copy:
    content: |
      user:
        {{ ansible_ssh_user }}:
          exists: true
          groups:
            - "{{ sudo_wheel }}"
      group:
        {{ sudo_wheel }}:
          exists: true
      file:
        /etc/sudoers:
          exists: true
          mode: "0440"
          contains:
      {% if sudo_ask_pass | bool %}
            - "%{{ sudo_wheel }} ALL=(ALL) ALL"
      {% else %}
            - "%{{ sudo_wheel }} ALL=(ALL) NOPASSWD: ALL"
      {% endif %}
    dest: "{{ goss_workdir }}/sudo.yml"
