---
- name: gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
  - "_{{ ansible_hostname }}.yml"
  - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_architecture | lower }}/{{ ansible_os_family | lower }}.yml"
  - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_os_family | lower }}.yml"
  tags: [ always ]

- name: install crond
  become: yes
  package:
    name: "{{ crond_package }}"

- name: auto start
  become: yes
  service:
    name: "{{ crond_service }}"
    state: started
    enabled: yes

- name: put gossfile
  become: yes
  template:
    src: goss.yml.j2
    dest: "{{ goss_dir }}/crond.yml"
    owner: root
    group: root
    mode: 0600
  when: goss_dir is defined
  tags: [ reconfigure ]
