---
- name: インストール手順の分岐
  include: "install_{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
  tags: [ always ]

- name: dockerグループを作成
  group:
    name: docker
  tags: [ docker ]

# - name: dockerグループに{{ ansible_ssh_user }}を追加
#   user:
#     name: "{{ ansible_ssh_user }}"
#     groups: docker
#     append: yes

- name: 自動起動
  service:
    name: docker
    state: started
    enabled: yes
  tags: [ docker, start ]

- name: テストファイルを配置
  copy:
    content: |
      service:
        docker:
          running: true
          enabled: true
      group:
        docker:
          exists: true
      file:
        /var/run/docker.sock:
          exists: true
          mode: "0660"
          owner: root
          group: docker
    dest: /usr/local/share/goss/docker.yml
  tags: [ docker, goss ]
