---
- name: postfix aliases
  become: yes
  command: newaliases

- name: postfix postmap sasl_password
  become: yes
  command: "postmap hash:{{ postfix_sasl_passwd_file }}"

- name: postfix reload
  become: yes

  service:
    name: postfix
    state: reloaded

- name: postfix restart
  become: yes
  service:
    name: postfix
    state: restarted
