---
# - hosts: ovh
#   become: yes
#   vars:
#     - sshd_ask_pass: no
#   roles:
#     - chrony
#     - sshd
#   post_tasks:
#     - pause:
#         seconds: 5
#     - name: run goss
#       shell: /usr/local/bin/goss -g /usr/local/share/goss/goss.yaml v
#       changed_when: False
#       tags: always

- hosts: OVH
  become: yes
  roles:
  - goss
  - chrony
  - wheel
  - sshd
  - ovh
  tasks:
  - include: "syncthing.yml"

# - hosts:
#   become: yes
#   tasks:
#   - include: "gitlab-runner.yml"
