---
# アーキテクチャを確認する
- name: gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_architecture | lower }}/{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: [ always ]

# ホスト名を確認する
- name: check if matches hostname and inventory
  assert:
    that: ansible_hostname == inventory_hostname
  when: ansible_connection != 'local'

# SELinux が無効になっていること
- name: check if selinux disabled
  assert:
    that: ansible_selinux.status == 'disabled'
  when: not ansible_selinux

# AppArmor が無効になっていること
- name: check if apparmor disabled
  shell: '[ ! "$(which aa-enabled > /dev/null && aa-enabled)" = "Yes" ]'
  changed_when: no

# インストールする
- name: install
  become: yes
  get_url:
    url: "https://github.com/aelsabbahy/goss/releases/download/v{{ goss_version }}/goss-{{ goss_arch }}"
    dest: "{{ goss_executable }}"
    owner: root
    group: root
    mode: 0700

# ファイルをすべて削除する
- name: erase all gossfiles
  become: yes
  file:
    path: "{{ goss_dir }}/"
    state: absent
  when: goss_always_rebuild

# ディレクトリを作成する
- name: make directory
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /usr/local/share/ansible/
    - "{{ goss_dir }}"

# モジュールをインストールする
- name: install ansible_goss module
  become: yes
  get_url:
    url: "https://raw.githubusercontent.com/indusbox/goss-ansible/{{ goss_ansible_goss_py_version }}/goss.py"
    dest: /usr/local/share/ansible/goss.py
    owner: root
    group: root
    mode: 0644

- name: put top-level gossfile
  become: yes
  template:
    src: goss.yaml
    dest: "{{ goss_dir }}/goss.yaml"
    owner: root
    group: root
    mode: 0600
