---
- name: アーキテクチャ別の変数を取り込む
  include_vars: "arch_{{ ansible_architecture }}.yml"
  tags: [ always ]

- name: 実行ファイルをインストール
  get_url:
    url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
    dest: "{{ goss_executable }}"
    mode: a+x
  tags: [ goss ]

- name: テストファイルを全て削除
  file:
    path: "{{ goss_workdir }}"
    state: absent
  when: goss_force_rebuild == True
  tags: [ goss ]

- name: ディレクトリを作成
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/local/share/ansible/
    - "{{ goss_workdir }}/"
  tags: [ goss ]

- name: ansibleのgossモジュールをインストール
  get_url:
    url: https://raw.githubusercontent.com/indusbox/goss-ansible/1.0.0/goss.py
    dest: /usr/local/share/ansible/goss.py
  tags: [ goss ]

- name: テストファイルを配置
  copy:
    content: |
      command:
        {{ goss_executable }} -v:
          exit-status: 0
          stdout:
          - "goss version {{ goss_version }}"
      gossfile:
        {{ goss_workdir }}/*.yml: {}
    dest: "{{ goss_workdir }}/goss.yaml"
  tags: [ goss ]
