---
- include_vars: "arch_{{ ansible_architecture }}.yml"

- name: install goss
  get_url:
    url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-{{ goss_arch }}"
    dest: "{{ goss_executable }}"
    mode: 0755

- name: remove all gossfiles
  file:
    path: "{{ goss_workdir }}"
    state: absent
  when: goss_rebuild_gossfiles

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/local/share/ansible/
    - "{{ goss_workdir }}/"

- name: install goss-ansible
  get_url:
    url: https://raw.githubusercontent.com/indusbox/goss-ansible/1.0.0/goss.py
    dest: /usr/local/share/ansible/goss.py
    mode: 0755

- name: put goss
  copy:
    dest: "{{ goss_workdir }}/goss.yaml"
    content: |
      command:
        {{ goss_executable }} -v:
          exit-status: 0
          stdout:
          - "goss version {{ goss_version }}"
      gossfile:
        {{ goss_workdir }}/*.yml: {}
