---
- name: アーキテクチャ別の変数を取り込む
  include_vars: "arch_{{ ansible_architecture }}.yml"
  tags: [ always ]

- name: 実行ファイルをインストール
  become: yes
  copy:
    owner: root
    mode: '0700'
    src: "goss-linux-{{ goss_arch }}_{{ goss_version }}"
    dest: "{{ goss_executable }}"

- name: テストファイルを全て削除
  become: yes
  file:
    path: "{{ goss_dir }}"
    state: absent
  when: goss_force_rebuild

- name: ディレクトリを作成
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /usr/local/share/ansible/
    - "{{ goss_dir }}/"

- name: ansibleのgossモジュールをインストール
  become: yes
  copy:
    src: goss.py
    dest: /usr/local/share/ansible/goss.py

- name: テストファイルを配置
  become: yes
  copy:
    owner: root
    mode: '0600'
    content: |
      command:
        {{ goss_executable }} -v:
          exit-status: 0
          stdout:
          - "goss version {{ goss_version }}"
      gossfile:
        {{ goss_dir }}/*.yml: {}
    dest: "{{ goss_dir }}/goss.yaml"
