---
- name: gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_hostname }}.yml"
    - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_architecture | lower }}/{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: [ always ]

- name: required variables
  assert:
    that:
    - prometheus_node_exporter_version != 'X.Y.Z'

- name: set fact
  set_fact:
    _prometheus_node_exporter_basename: "node_exporter-{{ prometheus_node_exporter_version }}.{{ prometheus_node_exporter_arch }}"

- name: download to local
  delegate_to: localhost
  become: no
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/\
          v{{ prometheus_node_exporter_version }}/{{ _prometheus_node_exporter_basename }}.tar.gz"
    dest: "/tmp/{{ _prometheus_node_exporter_basename }}.tar.gz"
  changed_when: no
  check_mode: no

- name: unpack to local
  delegate_to: localhost
  become: no
  unarchive:
    src: "/tmp/{{ _prometheus_node_exporter_basename }}.tar.gz"
    dest: "/tmp"
  changed_when: no
  check_mode: no

- name: install
  become: yes
  copy:
    src: "/tmp/{{ _prometheus_node_exporter_basename }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: '0755'
  with_items:
  - node_exporter

- block:
  - name: systemd service unit
    become: yes
    template:
      src: node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
      owner: root
      group: root
      mode: '0644'
    notify: prometheus-node-exporter restart
  - name: daemon reload
    systemd:
      name: node_exporter
      daemon_reload: yes
    notify: prometheus-node-exporter restart
  when: ansible_service_mgr == 'systemd'
  tags: [ configure ]

- name: auto start
  become: yes
  service:
    name: node_exporter
    state: started
    enabled: yes

- name: put gossfile
  become: yes
  template:
    src: goss.yml.j2
    dest: "{{ goss_dir }}/prometheus-node-exporter.yml"
    owner: root
    group: root
    mode: 0600
  when: goss_dir is defined
  tags: [ configure ]
