---

- name: set timezone
  timezone:
    name: Asia/Tokyo

- name: configure chrony.conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
    backup: yes
  notify: update ntp

- name: enable chronyd
  service:
    name: chronyd
    state: started
    enabled: yes
  notify: update ntp

- name: put goss
  copy:
    content: |
      service:
        chronyd:
          running: true
          enabled: true
    dest: /usr/local/share/goss/chrony.yml
