---

- name: create sshusers group
  group:
    name: sshusers

- name: append ansible_ssh_user to sshusers
  user:
    name: "{{ ansible_ssh_user }}"
    groups: sshusers
    append: yes

- name: put sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: start sshd
  service:
    name: sshd
    state: started
    enabled: yes

- name: put goss
  copy:
    content: |
      service:
        sshd:
          running: true
          enabled: true
      port:
        tcp:22:
          listening: true
          ip:
          - '0.0.0.0'
      # tcp6:22:
      #   listening: true
      #   ip:
      #   - '::'
      user:
        {{ ansible_ssh_user }}:
          exists: true
          groups:
          - sshusers
      group:
        sshusers:
          exists: true
    dest: /usr/local/share/goss/sshd.yml
