---
- name: backup /etc/ssh/sshd_config
  shell: cp -af /etc/ssh/sshd_config /etc/ssh/sshd_config.org
  args:
    creates: /etc/ssh/sshd_config.org

- name: groupadd sshusers
  group:
    name: sshusers

- name: "usermod -a -G sshusers {{ ansible_ssh_user }}"
  user:
    name: "{{ ansible_ssh_user }}"
    groups: sshusers
    append: yes

- name: set 'AllowGroups sshusers' in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#AllowGroups "
    regexp: "^AllowGroups "
    line: AllowGroups sshusers
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: set 'PasswordAuthentication {{ sshd_ask_pass }}' in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#PasswordAuthentication "
    regexp: "^PasswordAuthentication "
    line: "PasswordAuthentication {{ sshd_ask_pass }}"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: set 'ChallengeResponseAuthentication no' in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#ChallengeResponseAuthentication "
    regexp: "^ChallengeResponseAuthentication "
    line: ChallengeResponseAuthentication no
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: set 'PermitRootLogin {{ sshd_permit_root_login }}' in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#PermitRootLogin "
    regexp: "^PermitRootLogin "
    line: "PermitRootLogin {{ sshd_permit_root_login }}"
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: set 'UsePAM yes' in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: '^#UsePAM '
    regexp: "^UsePAM "
    line: UsePAM yes
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: set 'UseDNS no' in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    insertafter: "^#UseDNS "
    regexp: "^UseDNS "
    line: UseDNS no
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: start ssh service
  service:
    name: sshd
    state: started
    enabled: yes

- name: put goss
  copy:
    dest: /usr/local/share/goss/sshd.yml
    content: |
      service:
        sshd:
          running: true
          enabled: true
      port:
        tcp:22:
          listening: true
          ip:
          - '0.0.0.0'
      # tcp6:22:
      #   listening: true
      #   ip:
      #   - '::'
      user:
        {{ ansible_ssh_user }}:
          exists: true
          groups:
          - sshusers
      group:
        sshusers:
          exists: true
