---
- name: gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
  - "_{{ ansible_hostname }}.yml"
  - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_architecture | lower }}/{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_architecture | lower }}/{{ ansible_os_family | lower }}.yml"
  - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_distribution | lower }}.yml"
  - "{{ ansible_os_family | lower }}.yml"
  tags: [ always ]

- name:
  include: "install-{{ ansible_os_family | lower }}.yml"

- name: dockerグループを作成
  become: yes
  group:
    name: docker

# - name: join docker group
#   user:
#     name: "{{ ansible_ssh_user }}"
#     groups: docker
#     append: yes

- name: auto start
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

# - name: put goss file
#   copy:
#     content: |
#       service:
#         docker:
#           running: true
#           enabled: true
#       group:
#         docker:
#           exists: true
#       file:
#         /var/run/docker.sock:
#           exists: true
#           mode: "0660"
#           owner: root
#           group: docker
#     dest: /usr/local/share/goss/docker.yml
#   tags: [ docker, goss ]
