---
- name: prometheus-server reload
  become: true
  service:
    name: prometheus
    state: reloaded

- name: prometheus-server restart
  become: true
  service:
    name: prometheus
    state: restarted
