---
# 使用するバージョン
prometheus_node_exporter_version: X.Y.Z

# Listenアドレス
prometheus_node_exporter_listen_addr: '::'

# Listenポート
prometheus_node_exporter_listen_port: 9100

# コレクター
prometheus_node_exporter_collectors:
- arp
- bcache
- bonding
#- buddyinfo
- conntrack
- cpu
- cpufreq
- diskstats
#- drbd
- edac
- entropy
- filefd
- filesystem
- hwmon
- infiniband
- interrupts # official: disable
- ipvs
#- ksmd
- loadavg
- logind
#- mdadm # offical: enable
- meminfo
#- meminfo_numa
#- mountstats
- netclass
- netdev
- netstat
- nfs
- nfsd
- ntp # offical: disable
#- perf
- pressure
- processes # offical: disable
#- qdisc
#- runit
- sockstat
- stat
#- supervisord
- systemd # offical: disable
#- tcpstat
- textfile
- time
- timex
- uname
- vmstat
#- wifi
- xfs
#- zfs # offical: enable
