---
- name: required netaddr
  delegate_to: 'localhost'
  pip:
    name: netaddr

- name: gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_hostname }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags: [ always ]

# パッケージをインストールする
- name: install
  become: yes
  package:
    name: "{{ sshd_package }}"

# ホストキーを生成する
- name: generate host keys
  become: yes
  shell: |
    ssh-keygen -A
  args:
    creates: /etc/ssh/ssh_host_rsa_key

# 設定ファイルをバックアップする
- name: backup the original config file
  become: yes
  command: cp -af {{ sshd_config_file }} {{ sshd_config_file }}.orig
  args:
    creates: "{{ sshd_config_file }}.orig"

# sshusers グループを作成する
- name: create sshusers group
  become: yes
  group:
    name: sshusers

# Ansible ユーザは sshusers グループに属する
- name: join ansible_user to sshusers
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: sshusers
    append: yes

# 設定ファイルを作成する
- name: generate sshd_config
  become: yes
  template:
    src: sshd_config
    dest: "{{ sshd_config_file }}"
    owner: root
    group: root
    mode: "{{ sshd_config_file_perm }}"
    validate: "{{ sshd_executable }} -t -f %s"
  notify: sshd restart

# 自動的に起動する
- name: auto start
  become: yes
  service:
    name: "{{ sshd_service }}"
    state: started
    enabled: true

- name: get sha256 in sshd_config_file
  become: yes
  stat:
    path: "{{ sshd_config_file }}"
    checksum_algorithm: sha256
  register: _sshd_config_file_sha256

- name: put gossfile
  become: yes
  template:
    src: goss.yml
    dest: "{{ goss_dir }}/sshd.yml"
    owner: root
    group: root
    mode: 0600
  when: goss_dir is defined
