---
- name: required the systemd
  assert:
    that: ansible_service_mgr == 'systemd'

- name: download to localhost
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
  delegate_to: localhost

- name: unpack
  unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
  delegate_to: localhost

- name: install
  become: true
  copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - prometheus
    - promtool
  notify: prometheus restart

- name: create group
  become: true
  group:
    name: prometheus

- name: create user
  become: true
  user:
    name: prometheus
    group: prometheus
    shell: /sbin/nologin
    home: "{{ prometheus_db_dir }}"
    createhome: false

- name: make config directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: prometheus
    mode: 0750
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/conf.d"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/fule_sd"

- name: make db directory
  become: true
  file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755

- name: config
  become: true
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    owner: root
    group: root
    mode: 0644

- name: systemd service unit
  become: true
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify: prometheus restart

- name: start
  become: true
  systemd:
    name: prometheus.service
    state: started
    enabled: true
    daemon_reload: true
  notify: prometheus restart

- name: put gossfile
  become: true
  template:
    src: goss.yml.j2
    dest: "{{ goss_dir }}/prometheus-server.yml"
    owner: root
    group: root
    mode: 0600
  tags: [ goss ]
